version: 2
jobs:
  build:
    docker:
      - image: mvukov/ros-melodic-catkin:latest
    steps:
      - checkout:
          path: src
      - run:
          name: Build workspace
          command: |
            source /opt/ros/melodic/setup.bash
            catkin init
            catkin config --cmake-args -DCMAKE_BUILD_TYPE:STRING=Debug
            catkin build -j2 --no-status
      - run:
          name: Run tests
          command: |
            source /opt/ros/melodic/setup.bash
            source devel/setup.bash
            catkin run_tests qpoases_embedded -j1 --no-deps --no-status
            catkin_test_results build
