version: 2
jobs:
  build:
    docker:
      - image: mvukov/qpoases-embedded-ci:latest
    steps:
      - checkout:
          path: src
      - run:
          name: Build & Test
          command: |
            colcon build --event-handlers status- console_cohesion+ --cmake-args -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug
            colcon test --event-handlers status- console_cohesion+
            colcon test-result --all
